const THREE = window.THREE;

export function initLogisticsGlobe(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return null;
  
  container.innerHTML = '';

  const scene = new THREE.Scene();
  scene.fog = new THREE.FogExp2(0x02050f, 0.03); // Deep space fog for depth
  
  // Camera closer for massive feel
  const camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 1000);
  camera.position.set(0, 0, 16); // Closer than before

  const renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true });
  renderer.setSize(container.clientWidth, container.clientHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);

  const primaryGroup = new THREE.Group();
  // Center-left and dropped down slightly to make the northern hemisphere massive
  primaryGroup.position.set(-2.5, -2, 0); 
  primaryGroup.rotation.z = 23.5 * Math.PI / 180;
  scene.add(primaryGroup);

  const textureLoader = new THREE.TextureLoader();
  const earthTexture = textureLoader.load('/textures/earth-night.jpg');
  const bumpTexture = textureLoader.load('/textures/earth-topology.png');

  // ==========================================
  // LAYER 2: MASSIVE REALISTIC EARTH
  // ==========================================
  const GLOBE_RADIUS = 7; // Much bigger
  
  const globeGeometry = new THREE.SphereGeometry(GLOBE_RADIUS, 64, 64);
  const globeMaterial = new THREE.MeshStandardMaterial({
    map: earthTexture,
    bumpMap: bumpTexture,
    bumpScale: 0.2,
    roughness: 0.7,
    metalness: 0.1,
    emissive: 0x051025, // Deep blue core emittance
    emissiveIntensity: 0.3
  });
  const globe = new THREE.Mesh(globeGeometry, globeMaterial);
  primaryGroup.add(globe);

  // Atmospheric Soft Glow Shell
  const atmosGeometry = new THREE.SphereGeometry(GLOBE_RADIUS + 0.25, 64, 64);
  const atmosMaterial = new THREE.MeshPhongMaterial({
    color: 0x0ea5e9,
    emissive: 0x0ea5e9,
    emissiveIntensity: 0.5,
    transparent: true,
    opacity: 0.15,
    side: THREE.BackSide,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });
  const atmosphere = new THREE.Mesh(atmosGeometry, atmosMaterial);
  primaryGroup.add(atmosphere);

  // ==========================================
  // LAYER 3: CINEMATIC DYNAMIC NETWORK (MIMICS IMAGE)
  // ==========================================
  // We use an Icosahedron to create a perfect geodesic web wrapping the Earth
  const networkGroup = new THREE.Group();
  primaryGroup.add(networkGroup);
  
  const netRadius = GLOBE_RADIUS + 0.1;
  const netGeo = new THREE.IcosahedronGeometry(netRadius, 3); // Level 3 detail
  
  // 1. The glowing connecting grid lines
  const wireMat = new THREE.LineBasicMaterial({
    color: 0x22d3ee, // Bright cyan neon
    transparent: true,
    opacity: 0.25,
    blending: THREE.AdditiveBlending
  });
  const wireframe = new THREE.LineSegments(new THREE.WireframeGeometry(netGeo), wireMat);
  networkGroup.add(wireframe);

  // 2. The intense glowing nodes at vertices
  // We extract unique vertices from the BufferGeometry
  const posAttribute = netGeo.getAttribute('position');
  const vertexMap = new Set();
  const uniqueNodes = [];
  
  for(let i=0; i<posAttribute.count; i++) {
    const x = posAttribute.getX(i);
    const y = posAttribute.getY(i);
    const z = posAttribute.getZ(i);
    // Rough rounding to clear duplicate vertices generated by geometry seams
    const key = `${x.toFixed(2)},${y.toFixed(2)},${z.toFixed(2)}`;
    if(!vertexMap.has(key)) {
      vertexMap.add(key);
      uniqueNodes.push(new THREE.Vector3(x, y, z));
    }
  }

  // Draw bright nodes at intersections
  const nodeGeo = new THREE.SphereGeometry(0.06, 8, 8);
  const nodeMat = new THREE.MeshBasicMaterial({ 
    color: 0xffffff, 
    transparent: true, 
    opacity: 0.9 
  });
  const glowNodeMat = new THREE.MeshBasicMaterial({
    color: 0x22d3ee,
    transparent: true,
    opacity: 0.6,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });

  const nodeInstanced = new THREE.InstancedMesh(nodeGeo, nodeMat, uniqueNodes.length);
  const pseudoBloomGeo = new THREE.SphereGeometry(0.2, 8, 8);
  const glowInstanced = new THREE.InstancedMesh(pseudoBloomGeo, glowNodeMat, uniqueNodes.length);

  const tempMatrix = new THREE.Matrix4();
  uniqueNodes.forEach((pos, i) => {
    tempMatrix.setPosition(pos);
    nodeInstanced.setMatrixAt(i, tempMatrix);
    glowInstanced.setMatrixAt(i, tempMatrix);
  });
  
  networkGroup.add(nodeInstanced);
  networkGroup.add(glowInstanced);


  // ==========================================
  // LAYER 1 & 4: DEEP SPACE & FOREGROUND PARALLAX PARTICLES
  // ==========================================
  const particlesGroup = new THREE.Group();
  scene.add(particlesGroup);
  
  const pCount = 1500;
  const pGeo = new THREE.BufferGeometry();
  const pPos = new Float32Array(pCount * 3);
  const pSpeeds = [];
  
  for(let i=0; i<pCount*3; i+=3){
    // Spread them far out for depth
    pPos[i] = (Math.random() - 0.5) * 80;
    pPos[i+1] = (Math.random() - 0.5) * 80;
    pPos[i+2] = (Math.random() - 0.5) * 80;
    pSpeeds.push({
      x: (Math.random() - 0.5) * 0.02,
      y: (Math.random() - 0.5) * 0.02
    });
  }
  pGeo.setAttribute('position', new THREE.BufferAttribute(pPos, 3));
  
  // Mixed size stars and streaks for immersion
  const pMat = new THREE.PointsMaterial({
    color: 0x7dd3fc,
    size: 0.15,
    transparent: true,
    opacity: 0.7,
    blending: THREE.AdditiveBlending,
    depthWrite: false
  });
  
  const particleSys = new THREE.Points(pGeo, pMat);
  particlesGroup.add(particleSys);

  // Lighting to pop the ridges
  const ambientLight = new THREE.AmbientLight(0xffffff, 0.08); // Very dark ambient
  scene.add(ambientLight);
  
  const sunLight = new THREE.DirectionalLight(0xffffff, 2.0);
  sunLight.position.set(-20, 10, 25); // Hard light from front top left
  scene.add(sunLight);

  const rimLight = new THREE.DirectionalLight(0x0ea5e9, 2.5);
  rimLight.position.set(30, -10, -30); // Deep neon blue wrapping around back
  scene.add(rimLight);

  // ==========================================
  // MOUSE TRACKING FOR PARALLAX INTERACTION
  // ==========================================
  let mouseX = 0;
  let mouseY = 0;
  let targetX = 0;
  let targetY = 0;
  
  const windowHalfX = window.innerWidth / 2;
  const windowHalfY = window.innerHeight / 2;

  function onDocumentMouseMove(event) {
    mouseX = (event.clientX - windowHalfX) * 0.0005;
    mouseY = (event.clientY - windowHalfY) * 0.0005;
  }
  
  document.addEventListener('mousemove', onDocumentMouseMove, false);

  // ==========================================
  // CINEMATIC ANIMATION ENGINE
  // ==========================================
  let animationId;
  let startTime = Date.now();
  
  function animate() {
    animationId = requestAnimationFrame(animate);
    const elapsed = Date.now() - startTime;

    // Smoothly interpolate targets for buttery parallax
    targetX += (mouseX - targetX) * 0.05;
    targetY += (mouseY - targetY) * 0.05;

    // 1. Earth Rotation + Mouse Parallax
    primaryGroup.rotation.y += 0.0004; // base rotation
    // Add interactive tilt
    primaryGroup.rotation.y += targetX * 0.5;
    primaryGroup.rotation.x += (targetY * 0.5 - primaryGroup.rotation.x) * 0.05;
    
    // 2. Parallax Starflow (Moves opposite to camera/globe to increase depth)
    particlesGroup.rotation.y += 0.0001; 
    particlesGroup.rotation.x += 0.00005;
    particlesGroup.position.x += (targetX * 5 - particlesGroup.position.x) * 0.02;
    particlesGroup.position.y += (-targetY * 5 - particlesGroup.position.y) * 0.02;
    
    // 3. Network Pulsing
    wireMat.opacity = 0.15 + (Math.sin(elapsed * 0.001) + 1) * 0.1;
    glowInstanced.material.opacity = 0.4 + (Math.cos(elapsed * 0.0015) + 1) * 0.2;

    // 4. Cinematic Camera Breathing
    camera.position.z = 16 + Math.sin(elapsed * 0.0002) * 1.5;
    camera.position.x = Math.cos(elapsed * 0.0001) * 0.5;

    renderer.render(scene, camera);
  }

  animate();

  function onWindowResize() {
    camera.aspect = container.clientWidth / container.clientHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(container.clientWidth, container.clientHeight);
  }
  
  window.addEventListener('resize', onWindowResize, false);

  return {
    destroy: () => {
      cancelAnimationFrame(animationId);
      window.removeEventListener('resize', onWindowResize);
      document.removeEventListener('mousemove', onDocumentMouseMove);
      renderer.dispose();
      container.innerHTML = '';
    }
  };
}
